# Generated by Django 2.0.3 on 2018-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
